import json
rows = []

rows.append(dict(
 key="hk_1599", topic="기업·산업", format="이슈 분석",
 headline="한·중·일 반도체 삼국지",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="사실적 3D·CG", subject="지도·지구", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="부감·평면도", background="사실적 장면",
 image_area="풀블리드", vr_structure="융합", vr_meaning="연결(환유·연상)",
 key_symbols="회로기판·반도체 칩으로 된 동아시아 지도(중국·한반도·일본·대만), 오성홍기·태극기·일장기, 우주에서 본 지구와 수평선 햇빛",
 reference="삼국지(표제의 고전 차용)",
 layout="풀블리드 장면형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="화면 전체", salience="메인 표제",
 balance="비대칭 균형", depth="깊은 원근", whitespace="보통",
 bg_hue="파랑·남색", bg_value="어두움", harmony="보색 대비", itten="한난",
 headline_color="노랑·금색", accent="표제 강조",
 font_class="고딕", weight="아주 굵게", headline_size="4~7%", effect="그림자",
 emphasis="색 바꿈", type_image="이미지 위 오버레이",
 sentence="명사구", verbal_device="비유", tone="중립·정보", script_mix="한글만",
 anchorage="중복", dependency="가능",
 calm_dynamic=3, serious_playful=2, minimal_maximal=4, negative_positive=3,
 archetype="개념 은유형"))

rows.append(dict(
 key="hk_1601", topic="기술·AI", format="이슈 분석",
 headline="피지컬 AI 핵심 밸류체인",
 masthead_color="검정", masthead_overlap="이미지가 제호 일부를 가림",
 secondary_lines=2, headline_lines=3, subhead="없음", badge="있음", boxout="없음",
 medium="사실적 3D·CG", subject="사물·오브젝트", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="정면·아이레벨", background="단색 평면",
 image_area="30~60%", vr_structure="병치", vr_meaning="유사 비교(은유)",
 key_symbols="반쪽은 흰 외피·반쪽은 내부 기계가 드러난 휴머노이드 로봇, 인체 해부 이미지 세로 띠(뇌·흉곽·근육·신경세포·배터리·관절), 홀로그램 씰 배지('로봇 산업 대해부')",
 reference="없음",
 layout="분할형", headline_v="하단 1/3", headline_align="왼쪽",
 ideal_real="좌우 배치", subject_pos="오른쪽", salience="메인 표제",
 balance="비대칭 균형", depth="얕은 겹침", whitespace="보통",
 bg_hue="무채색", bg_value="밝음", harmony="무채색+포인트", itten="채도",
 headline_color="기타", accent="표제 강조",
 font_class="고딕", weight="아주 굵게", headline_size="7% 이상", effect="없음",
 emphasis="크기 대비", type_image="분리",
 sentence="명사구", verbal_device="없음", tone="중립·정보", script_mix="영문 포함",
 anchorage="정박", dependency="가능",
 calm_dynamic=2, serious_playful=2, minimal_maximal=4, negative_positive=4,
 archetype="개념 은유형"))

rows.append(dict(
 key="hk_1603", topic="금융업·금융인", format="전망·트렌드",
 headline="5대 금융지주 다음 25년을 묻다",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="사진 합성", subject="실존 인물", people_n="2~5", people_kind="실존 인물 사진",
 shot="미디엄", gaze="요구(정면 응시)", angle="정면·아이레벨", background="단색 평면",
 image_area="30~60%", vr_structure="병치", vr_meaning="연결(환유·연상)",
 key_symbols="5대 금융지주 회장 5인 상반신 사진, 각 그룹 CI 로고(KB·신한·하나·우리·NH농협), 그룹 상징색 세로 띠 5개",
 reference="없음",
 layout="인물 그리드형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="화면 전체", salience="메인 표제",
 balance="대칭", depth="얕은 겹침", whitespace="보통",
 bg_hue="파랑·남색", bg_value="중간", harmony="다색", itten="색상",
 headline_color="기타", accent="표제 강조",
 font_class="혼용", weight="아주 굵게", headline_size="4~7%", effect="여러 효과",
 emphasis="색 바꿈", type_image="분리",
 sentence="서술", verbal_device="숫자", tone="중립·정보", script_mix="숫자 포함",
 anchorage="중복", dependency="가능",
 calm_dynamic=2, serious_playful=2, minimal_maximal=4, negative_positive=4,
 archetype="인물 명단형"))

rows.append(dict(
 key="hk_1604", topic="기술·AI", format="투자 가이드·전략",
 headline="대한민국 미래 책임질 7대 첨단기술 투자지도",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=2, headline_lines=3, subhead="없음", badge="없음", boxout="없음",
 medium="사실적 3D·CG", subject="사물·오브젝트", people_n="1", people_kind="그림·실루엣·미니어처",
 shot="원경·소형", gaze="제공(비응시)", angle="정면·아이레벨", background="사실적 장면",
 image_area="풀블리드", vr_structure="병치", vr_meaning="연결(환유·연상)",
 key_symbols="빛 점으로 된 한반도 지도, 7대 기술 원형 이미지(SMR·핵융합·재생에너지·양자·우주항공·첨단바이오·핵심광물·소부장), 서울 야경 스카이라인(롯데월드타워·N서울타워·국회), 서울에서 뻗어 나가는 빛줄기",
 reference="없음",
 layout="풀블리드 장면형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구와 이미지 겹침", subject_pos="중앙", salience="메인 표제",
 balance="대칭", depth="깊은 원근", whitespace="좁음",
 bg_hue="파랑·남색", bg_value="어두움", harmony="단색조", itten="보색",
 headline_color="노랑·금색", accent="표제 강조",
 font_class="혼용", weight="아주 굵게", headline_size="4~7%", effect="여러 효과",
 emphasis="색 바꿈", type_image="이미지 위 오버레이",
 sentence="명사구", verbal_device="숫자", tone="기회·낙관", script_mix="숫자 포함",
 anchorage="중복", dependency="가능",
 calm_dynamic=4, serious_playful=2, minimal_maximal=5, negative_positive=5,
 archetype="개념 은유형"))

rows.append(dict(
 key="hk_1606", topic="거시경제·금리·환율", format="이슈 분석",
 headline="세계경제 긴축의 시대 금리인상에 흔들리는 글로벌 증시",
 masthead_color="검정", masthead_overlap="이미지가 제호 일부를 가림",
 secondary_lines=3, headline_lines=2, subhead="있음", badge="없음", boxout="없음",
 medium="사실적 3D·CG", subject="사물·오브젝트", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="정면·아이레벨", background="질감·패턴",
 image_area="60~90%", vr_structure="융합", vr_meaning="유사 비교(은유)",
 key_symbols="'DEBT'가 새겨진 빨간 철거용 쇠공(레킹볼)과 쇠사슬, 갈라지는 세계지도, 국기가 그려진 돌 파편(미국·한국·일본·EU)",
 reference="없음",
 layout="중앙 오브젝트형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="중앙", salience="주 이미지",
 balance="대칭", depth="깊은 원근", whitespace="보통",
 bg_hue="무채색", bg_value="밝음", harmony="무채색+포인트", itten="채도",
 headline_color="노랑·금색", accent="핵심 사물 강조",
 font_class="고딕", weight="아주 굵게", headline_size="4~7%", effect="여러 효과",
 emphasis="색 바꿈", type_image="이미지 위 오버레이",
 sentence="명사구", verbal_device="없음", tone="경고·위기", script_mix="한글만",
 anchorage="정박", dependency="가능",
 calm_dynamic=5, serious_playful=2, minimal_maximal=3, negative_positive=1,
 archetype="개념 은유형"))

rows.append(dict(
 key="mk_2366", topic="기업·산업", format="전망·트렌드",
 headline="AI 시대 ‘팹 골드러시’",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=1, subhead="없음", badge="없음", boxout="없음",
 medium="사진 합성", subject="사물·오브젝트", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="정면·아이레벨", background="질감·패턴",
 image_area="30~60%", vr_structure="융합", vr_meaning="유사 비교(은유)",
 key_symbols="회로기판(PCB)·반도체 칩으로 만든 곡괭이, 금빛 회로 패턴 배경",
 reference="골드러시(곡괭이·삽을 파는 쪽이 돈을 번다는 격언)",
 layout="중앙 오브젝트형", headline_v="상단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="중앙", salience="주 이미지",
 balance="대칭", depth="평면", whitespace="보통",
 bg_hue="주황·노랑·금색", bg_value="중간", harmony="단색조", itten="명암",
 headline_color="흰색", accent="제호 색과 호응",
 font_class="고딕", weight="굵게", headline_size="4~7%", effect="없음",
 emphasis="따옴표", type_image="분리",
 sentence="명사구", verbal_device="비유", tone="기회·낙관", script_mix="영문 포함",
 anchorage="정박", dependency="문구가 있어야 가능",
 calm_dynamic=2, serious_playful=3, minimal_maximal=2, negative_positive=4,
 archetype="개념 은유형"))

rows.append(dict(
 key="mk_2367", topic="정책·정치", format="이슈 분석",
 headline="K반도체 흔드는 ‘칩 폴리틱스’",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="사실적 3D·CG", subject="지도·지구", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="부감·평면도", background="그라데이션·조명",
 image_area="30~60%", vr_structure="융합", vr_meaning="연결(환유·연상)",
 key_symbols="회로기판(PCB)으로 만든 남한 지도, 위치 핀(금색 핀과 '호남' 칩), 반도체 칩, 제주 칩·울릉 콘덴서, 원근 격자 바닥",
 reference="없음",
 layout="중앙 오브젝트형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="중앙", salience="주 이미지",
 balance="비대칭 균형", depth="깊은 원근", whitespace="넓음",
 bg_hue="파랑·남색", bg_value="중간", harmony="보색 대비", itten="보색",
 headline_color="흰색", accent="제호 색과 호응",
 font_class="고딕", weight="굵게", headline_size="4~7%", effect="없음",
 emphasis="따옴표", type_image="분리",
 sentence="명사구", verbal_device="조어·신조어", tone="경고·위기", script_mix="영문 포함",
 anchorage="정박", dependency="가능",
 calm_dynamic=2, serious_playful=2, minimal_maximal=3, negative_positive=2,
 archetype="개념 은유형"))

rows.append(dict(
 key="mk_2370", topic="기업·산업", format="이슈 분석",
 headline="현대차 자동차냐 로봇이냐",
 masthead_color="흰색", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="사진 합성", subject="사물·오브젝트", people_n="0", people_kind="없음",
 shot="해당 없음", gaze="해당 없음", angle="정면·아이레벨", background="그라데이션·조명",
 image_area="30~60%", vr_structure="병치", vr_meaning="대립 비교(대조)",
 key_symbols="시소(저울) 양 끝의 자동차와 휴머노이드 로봇, 배경에 드리운 현대차 'H' 로고 그림자, 스포트라이트",
 reference="없음",
 layout="중앙 오브젝트형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="중앙", salience="주 이미지",
 balance="대칭", depth="얕은 겹침", whitespace="넓음",
 bg_hue="파랑·남색", bg_value="어두움", harmony="보색 대비", itten="보색",
 headline_color="흰색", accent="제호 색과 호응",
 font_class="고딕", weight="굵게", headline_size="4~7%", effect="없음",
 emphasis="크기 대비", type_image="분리",
 sentence="질문", verbal_device="대구·대조", tone="중립·정보", script_mix="한글만",
 anchorage="중복", dependency="가능",
 calm_dynamic=2, serious_playful=3, minimal_maximal=2, negative_positive=3,
 archetype="개념 은유형"))

rows.append(dict(
 key="mk_2372", topic="증시·투자", format="이슈 분석",
 headline="올라도 내려도 ‘코스피 블루’",
 masthead_color="검정", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="2D 일러스트", subject="숫자·기호·문자", people_n="2~5", people_kind="그림·실루엣·미니어처",
 shot="원경·소형", gaze="제공(비응시)", angle="하이 앵글", background="그라데이션·조명",
 image_area="30~60%", vr_structure="병치", vr_meaning="유사 비교(은유)",
 key_symbols="빨간(상승)·파란(하락) 입체 화살표 더미, 머리를 감싸 쥐고 좌절한 투자자들, 서류가방 든 남성의 뒷모습",
 reference="없음",
 layout="풀블리드 장면형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="화면 전체", salience="주 이미지",
 balance="대각선·동세", depth="얕은 겹침", whitespace="보통",
 bg_hue="파랑·남색", bg_value="밝음", harmony="보색 대비", itten="한난",
 headline_color="검정", accent="핵심 사물 강조",
 font_class="고딕", weight="굵게", headline_size="4~7%", effect="없음",
 emphasis="따옴표", type_image="분리",
 sentence="명사구", verbal_device="대구·대조", tone="경고·위기", script_mix="한글만",
 anchorage="중복", dependency="가능",
 calm_dynamic=4, serious_playful=3, minimal_maximal=4, negative_positive=2,
 archetype="데이터·기호형"))

rows.append(dict(
 key="mk_2373", topic="부동산", format="이슈 분석",
 headline="부동산 세제 개편 카오스",
 masthead_color="검정", masthead_overlap="겹치지 않음",
 secondary_lines=3, headline_lines=2, subhead="없음", badge="없음", boxout="없음",
 medium="2D 일러스트", subject="건축·도시·풍경", people_n="1", people_kind="그림·실루엣·미니어처",
 shot="미디엄", gaze="제공(비응시)", angle="정면·아이레벨", background="질감·패턴",
 image_area="30~60%", vr_structure="융합", vr_meaning="유사 비교(은유)",
 key_symbols="기울어진 아파트 건물들, 찢어진 종이 라벨('양도세'·'실거주'·'종부세'), 머리를 감싸 쥔 남성의 뒷모습, 회색 콘크리트 질감",
 reference="없음",
 layout="풀블리드 장면형", headline_v="중단 1/3", headline_align="가운데",
 ideal_real="문구 위·이미지 아래", subject_pos="화면 전체", salience="주 이미지",
 balance="대각선·동세", depth="얕은 겹침", whitespace="보통",
 bg_hue="무채색", bg_value="중간", harmony="무채색+포인트", itten="명암",
 headline_color="검정", accent="제호 색과 호응",
 font_class="고딕", weight="굵게", headline_size="4~7%", effect="없음",
 emphasis="크기 대비", type_image="분리",
 sentence="명사구", verbal_device="없음", tone="경고·위기", script_mix="한글만",
 anchorage="중복", dependency="가능",
 calm_dynamic=4, serious_playful=3, minimal_maximal=3, negative_positive=2,
 archetype="개념 은유형"))

with open('/home/claude/covers/analysis/coder2_B.jsonl','w',encoding='utf-8') as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False)+'\n')
print('wrote', len(rows))
